In [14]:
import torch

tensor_size = (8, 8)
block_shape = (4, 4)

# Generate random integers (0 or 1) with torch.randint
random_integers = torch.randint(2, size=tensor_size, dtype=torch.int)

# Convert the integers to boolean values
unstructured_outlier_mask = random_integers.bool()
matrix_blocks = unstructured_outlier_mask.view(int(tensor_size[0]/block_shape[0]), block_shape[0], int(tensor_size[1]/block_shape[1]), block_shape[1])
count_per_block = torch.sum(matrix_blocks, dim=(1, 3))

block_mask = count_per_block > 8
block_mask = block_mask.view(int(tensor_size[0]/block_shape[0]), int(tensor_size[1]/block_shape[1]))


tensor([[ True,  True,  True,  True, False, False,  True, False],
        [False, False,  True, False,  True,  True,  True, False],
        [False,  True, False,  True, False,  True, False,  True],
        [ True,  True, False,  True, False, False, False, False],
        [False,  True,  True,  True, False, False,  True, False],
        [False,  True, False, False,  True, False,  True, False],
        [False, False, False, False,  True,  True, False,  True],
        [False,  True, False,  True,  True,  True,  True, False]])
tensor([[ True, False],
        [False,  True]])


In [17]:
block_mask = count_per_block > 5
block_mask = block_mask.view(int(tensor_size[0]/block_shape[0]), int(tensor_size[1]/block_shape[1]))
print(block_mask)
print(count_per_block)

tensor([[True, True],
        [True, True]])
tensor([[10,  6],
        [ 6,  9]])
